Add the get /me route
ktp-alpha-class/clubhub pull request #28
Opened 2024-11-08 03:09 UTC by cooper-ke

should follow proper protocol!

2024-11-08 19:31 UTC, michael-brennan2005 requested changes

2024-11-08 19:31 UTC, michael-brennan2005 commented on backend/routes/user.py
> +    @app.route("/user/<user_id>")
wrong route do /me,
also specify this is a GET endpoint https://flask.palletsprojects.com/en/stable/quickstart/#http-methods

2024-11-08 19:31 UTC, michael-brennan2005 commented on backend/routes/user.py
> +    def get_me(user_id):
do get_user

2024-11-08 19:31 UTC, michael-brennan2005 commented on backend/routes/user.py
> +                supabase.table("Users")
- Table is now users
- With how auth works, you shouldnt be looking for where user_id == passed in user id, but where supabase_id == passed in supabase id

2024-11-08 19:31 UTC, michael-brennan2005 commented on backend/routes/user.py
> +            return jsonify({"user": response.data[0]}), 200
I think for this just return response.data[0], dont do a user key thing

2024-11-08 19:31 UTC, michael-brennan2005 commented on backend/routes/user.py
> +            return jsonify({"error": str(e)}), 400
Should be a 500 error

Like the error handling with this though good call

2024-11-12 18:57 UTC, cooper-ke commented on backend/routes/user.py
> +    def get_me(user_id):
done

2024-11-12 18:58 UTC, cooper-ke commented on backend/routes/user.py
> +                supabase.table("Users")
fixed capialization, updated to .eq("supabase_id", user_id) -- but should I change the name of user_id to supabase_id?

2024-11-12 18:58 UTC, cooper-ke commented on backend/routes/user.py
> +            return jsonify({"user": response.data[0]}), 200
done

2024-11-12 18:58 UTC, cooper-ke commented on backend/routes/user.py
> +            return jsonify({"error": str(e)}), 400
done

2024-11-12 18:59 UTC, cooper-ke commented on backend/routes/user.py
> +    def get_me(user_id):
well, changed get_me => get_user, is @authenticate_user correct?

2024-11-16 16:36 UTC, merged